image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaImcEditor" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaImcEditor\XwaImcEditor.sln

build:
  project: XwaImcEditor\XwaImcEditor.sln
  verbosity: minimal

after_build:
- XwaImcEditor\build-dist.cmd

artifacts:
- path: XwaImcEditor\dist
  name: XwaImcEditor-$(APPVEYOR_BUILD_VERSION)
  type: zip
